### ISSUE TITLE
Add title/menu bar?

### ISSUE THREAD

**Issue by renatodeleao** [tomasmcm/SpotiWeb#1]
Sorry I'm addicted to fullscreen apps on Mac.

**Comment by tomasmcm** [comment]
The title bar was purposefully removed to simulate the look on the Desktop App. There are other ways to allow for fullscreen mode. 
Added to Improvements!

**Comment by tomasmcm** [comment]
Fixed in https://github.com/tomasmcm/SpotiWeb/releases/tag/v0.2.0
Closing ✔️
