### ISSUE TITLE
SpotiWeb goes to black and music stops

### ISSUE THREAD

**Issue by dragonxtek** [tomasmcm/SpotiWeb#11]
After 50 minutes aprox (I've only tried twice) the window goes to black and the music stops.
The console don't show me any information about this bug

> medianexttrack registration failed
> mediaplaypause registration failed
> mediaprevioustrack registration failed
> NOT SANDBOXED
> Vector smash protection is enabled.

![i love summer - persian raver remix - domy pirelli - spotify_044](https://cloud.githubusercontent.com/assets/10552658/18727333/88ecb2a6-801e-11e6-8399-d8d4c194a3c9.png)

**Comment by tomasmcm** [comment]
@dragonxtek can you try playing music through your normal browser at play.spotify.com to check if this issue is from this app or from spotify itself (the web player has not been updated in a while so there are many bugs...)

**Comment by dragonxtek** [comment]
I had the same problem on the web (the music stops), for this reason I want to use a client. With the official spotify app I don't have this problem.

**Comment by tomasmcm** [comment]
@dragonxtek this client is a wrapper of the web version so if this happens in the web version it will happen in the desktop app as well.

**Comment by tomasmcm** [comment]
I'm closing this due to the fact that the bug is outside of SpotiWeb's scope.
