### ISSUE TITLE
The music stops 

### ISSUE THREAD

**Issue by dragonxtek** [tomasmcm/SpotiWeb#12]
When I'm listenig music, sometimes the music stops. It solves pressing play again. 
I don't know if the connection it's bad, traffic shaping or if it's a bug, but It would be a good idea to implement a persistent connection.

**Comment by tomasmcm** [comment]
@dragonxtek again, if you could please try playing music through your normal browser at play.spotify.com just to check if the problem is on my side or not.

**Comment by dragonxtek** [comment]
I had the same problem on the web (the music stops), for this reason I want to use a client. With the official spotify app I don't have this problem.

**Comment by tomasmcm** [comment]
This app is a wrapper of the web version, so if it happens in the web app it will happen in this desktop app as well.

**Comment by tomasmcm** [comment]
I'm closing this due to the fact that the bug is outside of SpotiWeb's scope.
