### ISSUE TITLE
There isn't option to repeat the same song

### ISSUE THREAD

**Issue by ownchoice** [tomasmcm/SpotiWeb#14]
There is an option to repeat the playlist, but not an option to repeat a single song.
The button works like this: with one click, it repeats the playlist, with another click, repeats nothing. But I would expect that after the second click, the button would change to "repeat the current song".

**Comment by tomasmcm** [comment]
@ownchoice this has to do with the way http://play.spotify.com is designed, if you can't do it there you won't be able to do it here. Sorry there is not much I can do about it...

**Comment by ownchoice** [comment]
I thought so, thanks for answering.
