### ISSUE TITLE
openSpotify compilation error

### ISSUE THREAD

**Issue by ikkecode** [tomasmcm/SpotiWeb#23]
When Im trying to create App binaries from openspotify branch, error occurs

> npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./ SpotiWeb --platform=darwin --arch=all --version=1.1.1 --app-version=$npm_package_version --build-version=$npm_package_version --out=./releases --asar=true --asar-unpack-dir=node_modules/ --overwrite=true --icon=./assets/icon.icns --ignore="releases|distributions|npm-debug.log|node_modules/(electron-(builder|packager|prebuilt)|devtron)|node_modules/electron-widevinecdm/dist/(libwidevinecdm.so|libwidevinecdmadapter.so|widevinecdm.dll|widevinecdmadapter.dll)

> [ixoos@Igor-Laptop
SpotiWeb-openSpotify]$ npm bugs spotiweb
npm ERR! code E404                                                                                                                                                     
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/spotiweb                                                                                      
npm ERR! 404                                                                                                                                                           
npm ERR! 404  'spotiweb' is not in the npm registry.                                                                                                                   
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)                                                                                       
npm ERR! 404                                                                                                                                                           
npm ERR! 404 Note that you can also install from a                                                                                                                     
npm ERR! 404 tarball, folder, http url, or git url.                                                                                                                    
npm ERR! A complete log of this run can be found in:

**Comment by tomasmcm** [comment]
@Ixoos The openSpotify branch is still not production ready, but you should be able to create binaries. When you run `npm start` are there any errors?

**Comment by ikkecode** [comment]
```
[ixoos@Igor-Laptop SpotiWeb-openSpotify]$ npm start                                                                                                                    
                                                                                                                                                                       
SpotiWeb@0.6.0 start /home/ixoos/.local/share/Trash/files/SpotiWeb-openSpotify (2)                                                                                   
electron main.js dev                                                                                                                                                 
medianexttrack registration failed                                                                                                                                     
mediaplaypause registration failed
mediaprevioustrack registration failed
```
