### ISSUE TITLE
Lyrics support

### ISSUE THREAD

**Issue by isaac0025** [tomasmcm/SpotiWeb#6]
Hi, 
I was thinking that adding lyrics suppport could be a cool feature for SpotiWeb, now that musixmatch isn't available on Spotify. 

Thanks!

**Comment by Quacky2200** [comment]
I've tried this with my client with my version of Spotify Web Player for Linux. Sadly MusixMatch knows about bots/scraping and are against it, although it did work for the first few hours. I looked at lyricsfreak too but their search is terrible. It looks like you either make a smart bot that searches every/makes it unknown that it's a bot, or use/create some service that's better.

https://github.com/Quacky2200/node-unofficialmxm/settings

**Comment by tomasmcm** [comment]
@sheldomy I'm glad to say that SpotiWeb v0.5 now allows you to search for Lyrics! Just click the lyrics button below the play button

**Comment by isaac0025** [comment]
Thank you, lyrics support works perfectly!!
