### ISSUE TITLE
Can't click on upper section

### ISSUE THREAD

**Issue by alagos** [tomasmcm/SpotiWeb#7]
I'm having an issue trying to click the menu options. For example, here in "Your Music" section I can't click all those "Songs", "Albums" and "Artists" links, even that "New playlist" button can't be clicked all the top middle of it:
![captura de pantalla_2016-09-05_23-41-03](https://cloud.githubusercontent.com/assets/475834/18260305/bf17f614-73c2-11e6-9c22-6bf75bd22500.png)

For this case, I don't have problems to access to options (I have the cursor on biography and you could see the color has changed)
![captura de pantalla_2016-09-05_23-50-48](https://cloud.githubusercontent.com/assets/475834/18260393/c4484d9a-73c3-11e6-9638-29e55e2fd17d.png)

But after scrolling down the songs list a bit, all the upper links become unaccessible, like pause/following buttons or overview/related artists/biography menu options
![captura de pantalla_2016-09-05_23-55-50](https://cloud.githubusercontent.com/assets/475834/18260456/607b45a0-73c4-11e6-954a-87ca8f5777f7.png)

BTW, I'm using Xubuntu 16.04.

**Comment by tomasmcm** [comment]
@alagos Hi there, can you check if this problem persists in SpotiWeb v0.5?

**Comment by alagos** [comment]
@tomasmcm now is working. Sweet!
