### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by dragonxtek** [tomasmcm/SpotiWeb#9]
I got this error:

> npm ERR! Linux 4.4.0-36-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> 
> npm ERR! electron-prebuilt@1.4.0 postinstall: `node install.js`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the electron-prebuilt@1.4.0 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron-prebuilt
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls electron-prebuilt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/dragonxtek/SpotiWeb/npm-debug.log

These are the most important lines from npm-debug-log:

> 21051 verbose stack Error: electron-prebuilt@1.4.0 postinstall: `node install.js`
> 21051 verbose stack spawn ENOENT
> 21051 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
> 21051 verbose stack     at emitTwo (events.js:87:13)
> 21051 verbose stack     at ChildProcess.emit (events.js:172:7)
> 21051 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 21051 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

I have the lastest nodejs and npm version (from ubuntu 16.04 repositories).
How can I solve it?

**Comment by tomasmcm** [comment]
@dragonxtek This looks like an issue with electron-prebuilt, can you try to install it globally `npm install -g electron-prebuilt` also try to install electron first `npm install -g electron`.

**Comment by dragonxtek** [comment]
I fixed it with the following commands:
`apt-get install nodejs`
`sudo ln -s nodejs node`
`sudo npm install -g electron`

Thanks
